db-uri = "postgresql://authenticator:POSTGREST_DB_PASSWORD@localhost:5432/yb_manager"
db-schema = "public"
db-anon-role = "anon"
db-pool = 10
db-pool-acquisition-timeout = 10

server-host = "127.0.0.1"
server-port = 3000

jwt-secret = "JWT_SECRET_PLACEHOLDER"
jwt-secret-is-base64 = false
jwt-aud = ""

log-level = "warn"
